version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /src/OpenPortal.Web/ClientApp
    schedule:
      interval: weekly
    groups:
      client:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
