// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenPortal.Audit.Infrastructure.Persistence;

#nullable disable

namespace OpenPortal.Web.Persistence.Migrations.Audit
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20261007195225_InitialAuditSchema")]
    partial class InitialAuditSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("OpenPortal.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLabel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("IX_AuditEntries_ActorId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditEntries_OccurredAtUtc");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("IX_AuditEntries_TargetId");

                    b.ToTable("AuditEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
